### ISSUE TITLE
PEP517 Build-system dependencies should be pinned for deterministic builds from source code

### ISSUE THREAD

**Issue by faph** [jborean93/pykrb5#15]
The migration to PEP517 is a good move. However, there are some edge cases whereby a `pip install`s from source code might fail.

Currently the build backend is configured like this:

```toml
[build-system]
requires = [
    "Cython >= 0.29.29, < 3.0.0",  # 0.29.29 includes fixes for Python 3.11
    "setuptools >= 61.0.0",  # Support for setuptools config in pyproject.toml
]
build-backend = "setuptools.build_meta"
```

This means, for example, than any new releases to `setuptools` could cause a `pip install` failure from source code when it's trying to build a wheel.

This is not only possible after a major version updates of setuptools. There are cases whereby other minor/micro changes could break the build, for example, depending on the exact Python installation.

For discussion: should the build system's dependencies be fully pinned at each release of `krb5` to ensure for a given source distribution a binary distribution can always be rebuild, exactly as was tested at the point of the release?
